# Simulated daily request to your render project so that the service doesn't go down
name: Daily render ping

on:
  schedule:
     - cron: '0 8 * * * ' # Runs daily at 8:00 am IST
     - cron: '45 10 * * * ' # Runs daily at 10.45 am IST
     - cron: '0 2 * * * ' # Runs daily at 2:00 pm IST
      
     
  workflow_dispatch:  # Allows manual triggering

jobs:
  curl-website:
    runs-on: ubuntu-latest

    steps:
      - name: Run cURL on Website
        run: curl -I https://cross-network-transfer.onrender.com/
